# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               ninja-1
tagline:             'A personal blog'
description:         'A personal blog'
url:                 https://blog.daltonmiller.me
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dalton Miller
  url:               https://daltonmiller.me
  email:             dalton@daltonmiller.me

# Custom vars
version:             1.0.0
